const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  const network = hre.network.name;
  const backendSigner = process.env.BACKEND_SIGNER_ADDRESS || deployer.address;

  console.log("═══════════════════════════════════════════════");
  console.log("  DAMM — Contract Deployment");
  console.log("═══════════════════════════════════════════════");
  console.log(`  Network : ${network}`);
  console.log(`  Deployer: ${deployer.address}`);

  const balance = await hre.ethers.provider.getBalance(deployer.address);
  console.log(`  Balance : ${hre.ethers.formatEther(balance)} ETH`);
  console.log("───────────────────────────────────────────────");

  // Deploy ModelRegistry
  console.log("  Step 1/6: Loading ModelRegistry factory...");
  const ModelRegistry = await hre.ethers.getContractFactory("ModelRegistry");
  console.log("  Step 2/6: Sending ModelRegistry deployment tx...");
  const registryContract = await ModelRegistry.deploy();
  console.log("  Step 3/6: Waiting for ModelRegistry confirmation...");
  const deploymentTx = registryContract.deploymentTransaction();
  if (!deploymentTx) {
    throw new Error("Deployment transaction was not created");
  }
  console.log(`  Tx Hash : ${deploymentTx.hash}`);

  let minedReceipt = null;
  for (let attempt = 0; attempt < 120; attempt += 1) {
    minedReceipt = await hre.ethers.provider.getTransactionReceipt(deploymentTx.hash);
    if (minedReceipt && minedReceipt.blockNumber) {
      break;
    }
    await sleep(3000);
  }

  if (!minedReceipt || !minedReceipt.blockNumber) {
    throw new Error("Deployment transaction was not confirmed in time");
  }

  const registryAddress = await registryContract.getAddress();
  console.log(`  ✓ ModelRegistry deployed to: ${registryAddress}`);

  // Deploy ModelLicense
  console.log("  Step 4/6: Loading ModelLicense factory...");
  const ModelLicense = await hre.ethers.getContractFactory("ModelLicense");
  console.log("  Step 5/6: Sending ModelLicense deployment tx...");
  const licenseContract = await ModelLicense.deploy(registryAddress, backendSigner);
  const licenseTx = licenseContract.deploymentTransaction();
  if (!licenseTx) {
    throw new Error("License deployment transaction was not created");
  }
  console.log(`  License Tx Hash : ${licenseTx.hash}`);

  let minedLicenseReceipt = null;
  for (let attempt = 0; attempt < 120; attempt += 1) {
    minedLicenseReceipt = await hre.ethers.provider.getTransactionReceipt(licenseTx.hash);
    if (minedLicenseReceipt && minedLicenseReceipt.blockNumber) {
      break;
    }
    await sleep(3000);
  }
  if (!minedLicenseReceipt || !minedLicenseReceipt.blockNumber) {
    throw new Error("License deployment transaction was not confirmed in time");
  }

  const licenseAddress = await licenseContract.getAddress();
  console.log(`  ✓ ModelLicense deployed to: ${licenseAddress}`);
  console.log("═══════════════════════════════════════════════\n");

  // ─── Save deployment info for the frontend ──────────────────
  const registryArtifactPath = path.resolve(
    __dirname,
    "../artifacts/contracts/ModelRegistry.sol/ModelRegistry.json"
  );
  const registryArtifact = JSON.parse(fs.readFileSync(registryArtifactPath, "utf-8"));

  const licenseArtifactPath = path.resolve(
    __dirname,
    "../artifacts/contracts/ModelLicense.sol/ModelLicense.json"
  );
  const licenseArtifact = JSON.parse(fs.readFileSync(licenseArtifactPath, "utf-8"));

  const deploymentInfo = {
    network: network,
    chainId: network === "sepolia" ? 11155111 : 31337,
    modelRegistryAddress: registryAddress,
    modelLicenseAddress: licenseAddress,
    deployer: deployer.address,
    backendSigner: backendSigner,
    deployedAt: new Date().toISOString(),
    modelRegistryAbi: registryArtifact.abi,
    modelLicenseAbi: licenseArtifact.abi,
  };

  // Save to contracts/deployment.json
  const deploymentPath = path.resolve(__dirname, "../deployment.json");
  fs.writeFileSync(deploymentPath, JSON.stringify(deploymentInfo, null, 2));
  console.log(`  Deployment info saved to: ${deploymentPath}`);

  // Also copy to frontend as contract-config.js for direct import
  const frontendDir = path.resolve(__dirname, "../../frontend");
  const configContent = `/**
 * Auto-generated by deploy.js — DO NOT EDIT MANUALLY.
 * Network: ${network} | Deployed: ${deploymentInfo.deployedAt}
 */
const MODEL_REGISTRY_CONFIG = ${JSON.stringify(
    {
      address: registryAddress,
      chainId: deploymentInfo.chainId,
      network: network,
    },
    null,
    2
  )};

const MODEL_LICENSE_CONFIG = ${JSON.stringify(
    {
      address: licenseAddress,
      chainId: deploymentInfo.chainId,
      network: network,
    },
    null,
    2
  )};

const MODEL_REGISTRY_ABI = ${JSON.stringify(registryArtifact.abi, null, 2)};
const MODEL_LICENSE_ABI = ${JSON.stringify(licenseArtifact.abi, null, 2)};
`;

  const frontendConfigPath = path.join(frontendDir, "contract-config.js");
  fs.writeFileSync(frontendConfigPath, configContent);
  console.log("  Step 6/6: Frontend contract config updated.");
  console.log(`  Frontend config saved to: ${frontendConfigPath}`);
}

main()
  .then(() => {
    // Let Node exit naturally after all I/O flushes.
  })
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
