const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  const network = hre.network.name;

  console.log("═══════════════════════════════════════════════");
  console.log("  DAMM — ModelRegistry Deployment");
  console.log("═══════════════════════════════════════════════");
  console.log(`  Network : ${network}`);
  console.log(`  Deployer: ${deployer.address}`);

  const balance = await hre.ethers.provider.getBalance(deployer.address);
  console.log(`  Balance : ${hre.ethers.formatEther(balance)} ETH`);
  console.log("───────────────────────────────────────────────");

  // Deploy
  console.log("  Step 1/4: Loading contract factory...");
  const ModelRegistry = await hre.ethers.getContractFactory("ModelRegistry");
  console.log("  Step 2/4: Sending deployment transaction...");
  const contract = await ModelRegistry.deploy();
  console.log("  Step 3/4: Waiting for confirmation...");
  const deploymentTx = contract.deploymentTransaction();
  if (!deploymentTx) {
    throw new Error("Deployment transaction was not created");
  }
  console.log(`  Tx Hash : ${deploymentTx.hash}`);

  let minedReceipt = null;
  for (let attempt = 0; attempt < 120; attempt += 1) {
    minedReceipt = await hre.ethers.provider.getTransactionReceipt(deploymentTx.hash);
    if (minedReceipt && minedReceipt.blockNumber) {
      break;
    }
    await sleep(3000);
  }

  if (!minedReceipt || !minedReceipt.blockNumber) {
    throw new Error("Deployment transaction was not confirmed in time");
  }

  const contractAddress = await contract.getAddress();
  console.log(`  ✓ ModelRegistry deployed to: ${contractAddress}`);
  console.log("═══════════════════════════════════════════════\n");

  // ─── Save deployment info for the frontend ──────────────────
  const artifactPath = path.resolve(
    __dirname,
    "../artifacts/contracts/ModelRegistry.sol/ModelRegistry.json"
  );
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf-8"));

  const deploymentInfo = {
    network: network,
    chainId: network === "sepolia" ? 11155111 : 31337,
    contractAddress: contractAddress,
    deployer: deployer.address,
    deployedAt: new Date().toISOString(),
    abi: artifact.abi,
  };

  // Save to contracts/deployment.json
  const deploymentPath = path.resolve(__dirname, "../deployment.json");
  fs.writeFileSync(deploymentPath, JSON.stringify(deploymentInfo, null, 2));
  console.log(`  Deployment info saved to: ${deploymentPath}`);

  // Also copy to frontend as contract-config.js for direct import
  const frontendDir = path.resolve(__dirname, "../../frontend");
  const configContent = `/**
 * Auto-generated by deploy.js — DO NOT EDIT MANUALLY.
 * Network: ${network} | Deployed: ${deploymentInfo.deployedAt}
 */
const CONTRACT_CONFIG = ${JSON.stringify(
    {
      address: contractAddress,
      chainId: deploymentInfo.chainId,
      network: network,
    },
    null,
    2
  )};

const CONTRACT_ABI = ${JSON.stringify(artifact.abi, null, 2)};
`;

  const frontendConfigPath = path.join(frontendDir, "contract-config.js");
  fs.writeFileSync(frontendConfigPath, configContent);
  console.log("  Step 4/4: Frontend contract config updated.");
  console.log(`  Frontend config saved to: ${frontendConfigPath}`);
}

main()
  .then(() => {
    // Let Node exit naturally after all I/O flushes.
  })
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
